/* Generated By:JavaCC: Do not edit this line. langXConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface langXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int EXTENDS = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int CHAR = 21;
  /** RegularExpression Id. */
  int BOOLEAN = 22;
  /** RegularExpression Id. */
  int DOUBLE = 23;
  /** RegularExpression Id. */
  int NEW = 24;
  /** RegularExpression Id. */
  int PRINT = 25;
  /** RegularExpression Id. */
  int READ = 26;
  /** RegularExpression Id. */
  int RETURN = 27;
  /** RegularExpression Id. */
  int SUPER = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int DO = 30;
  /** RegularExpression Id. */
  int SWITCH = 31;
  /** RegularExpression Id. */
  int CASE = 32;
  /** RegularExpression Id. */
  int DEFAULT_CASE = 33;
  /** RegularExpression Id. */
  int int_constant = 34;
  /** RegularExpression Id. */
  int float_constant = 35;
  /** RegularExpression Id. */
  int string_constant = 36;
  /** RegularExpression Id. */
  int boolean_constant = 37;
  /** RegularExpression Id. */
  int char_constant = 38;
  /** RegularExpression Id. */
  int null_constant = 39;
  /** RegularExpression Id. */
  int IDENT = 40;
  /** RegularExpression Id. */
  int LETTER = 41;
  /** RegularExpression Id. */
  int DIGIT = 42;
  /** RegularExpression Id. */
  int LPAREN = 43;
  /** RegularExpression Id. */
  int RPAREN = 44;
  /** RegularExpression Id. */
  int LBRACE = 45;
  /** RegularExpression Id. */
  int RBRACE = 46;
  /** RegularExpression Id. */
  int LBRACKET = 47;
  /** RegularExpression Id. */
  int RBRACKET = 48;
  /** RegularExpression Id. */
  int SEMICOLON = 49;
  /** RegularExpression Id. */
  int COMMA = 50;
  /** RegularExpression Id. */
  int DOT = 51;
  /** RegularExpression Id. */
  int COLON = 52;
  /** RegularExpression Id. */
  int ASSIGN = 53;
  /** RegularExpression Id. */
  int GT = 54;
  /** RegularExpression Id. */
  int LT = 55;
  /** RegularExpression Id. */
  int EQ = 56;
  /** RegularExpression Id. */
  int LE = 57;
  /** RegularExpression Id. */
  int GE = 58;
  /** RegularExpression Id. */
  int NEQ = 59;
  /** RegularExpression Id. */
  int PLUS = 60;
  /** RegularExpression Id. */
  int MINUS = 61;
  /** RegularExpression Id. */
  int STAR = 62;
  /** RegularExpression Id. */
  int SLASH = 63;
  /** RegularExpression Id. */
  int REM = 64;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 65;
  /** RegularExpression Id. */
  int INVALID_CONST = 66;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"int\"",
    "\"string\"",
    "\"char\"",
    "\"boolean\"",
    "\"double\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"super\"",
    "\"while\"",
    "\"do\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "<int_constant>",
    "<float_constant>",
    "<string_constant>",
    "<boolean_constant>",
    "<char_constant>",
    "<null_constant>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "<LPAREN>",
    "<RPAREN>",
    "<LBRACE>",
    "<RBRACE>",
    "<LBRACKET>",
    "<RBRACKET>",
    "<SEMICOLON>",
    "<COMMA>",
    "<DOT>",
    "<COLON>",
    "<ASSIGN>",
    "<GT>",
    "<LT>",
    "<EQ>",
    "<LE>",
    "<GE>",
    "<NEQ>",
    "<PLUS>",
    "<MINUS>",
    "<STAR>",
    "<SLASH>",
    "<REM>",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
